### ISSUE TITLE
坏掉的2020，坏掉的我自己，自救？ | Sanmisan's tree

### ISSUE THREAD

**Issue by sanmisanFan** [sanmisanFan/sanmisanFan.github.io#12]
https://sanmisanfan.github.io/2020/03/28/self-rescue/ 

 nlp,nrl,ne,foodforfun

**Comment by ghostviper** [comment]
嘿嘿 你好！可以的，我看到啦，你和我一样心思比较细腻呀~ 看了你的文章 写的可以的 继续加油！一起交流呀 我qq 583771987
